### ISSUE TITLE
Add support for Content Templates (Blueprints)

### ISSUE THREAD

**Issue by skttl** [umco/umbraco-doc-type-grid-editor#101]
as discussed in #99

**Comment by leekelleher** [comment]
@skttl **Wow** - thanks for PR #104! 🎉 #h5yr  I'll close this issue off, and we can feedback on the PR.

_It's looking like towards the end of this week before I can review it properly ...I've got some SagePay integration nonsense today 😖 and off-site meetings tomorrow._

**Comment by skttl** [comment]
No worries, I'm in no hurry :)
