### ISSUE TITLE
Error when inserting doc type grid editor in grid column

### ISSUE THREAD

**Issue by bjarnef** [umco/umbraco-doc-type-grid-editor#107]
I have a doc type with alias `campaignImageBox` and I have a partial in `/Partials/CampaignImageBox.cshtml`.

When I insert this in the grid I get an error. I am running on Umbraco v7.10.4 and DTGE v0.5.0

![chrome_2018-07-12_11-08-42](https://user-images.githubusercontent.com/2919859/42624090-d08c67de-85c4-11e8-9f0d-1e4d74a52f00.png)

```
Request error: The URL returned a 404 (not found): 
/19654
with data: 
"id=43cad35b-1320-8e26-e9c8-5644499fb76e&editorAlias=docType&contentTypeAlias=campaignImageBox&value=%7B%22name%22%3A%22Doc+Type%22%2C%22image%22%3A%22%22%2C%22heading%22%3A%22%22%2C%22description%22%3A%22%22%2C%22link%22%3A%5B%5D%7D&viewPath=%2FViews%2FPartials%2FGrid%2FEditors%2FDocTypeGridEditor%2F&previewViewPath=%2FViews%2FPartials%2FGrid%2FEditors%2FDocTypeGridEditor%2FPreviews%2F"
Contact your administrator for information.
```

**Comment by leekelleher** [comment]
Do you know if the node (with ID 19654) is published or not?  If it's unpublished, then this is a known issue with the previewer, (it's a big pain - sorry).

We're been trying to refactor it, (see #105 for latest efforts), but backwards-compatibility has proved to be tough on this one.

**Comment by leekelleher** [comment]
Hmmm... what do you have your `previewViewPath` set to in the config? (It'll try to fall back on using the `viewPath`).  Unless if you're using a custom `SurfaceController` for that editor, then that's another story?

**Comment by leekelleher** [comment]
Interesting... just had this on the forum: https://our.umbraco.com/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/92811-preview-mode-requires-disablefindcontentbyidpath-false

Where `disableFindContentByIdPath` in umbracoSettings.config is set to false (by default)? (First I'd heard of this)

**Comment by bjarnef** [comment]
I have the defaults in `/Config/grid.editors.config.js`

```
{
        "name": "Doc Type",
        "alias": "docType",
        "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
        "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
        "icon": "icon-item-arrangement",
        "config": {
            "allowedDocTypes": [],
            "nameTemplate": "",
            "enablePreview": true,
            "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
            "previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
            "previewCssFilePath": "",
            "previewJsFilePath": ""
        }
    }
```

**Comment by bjarnef** [comment]
I have this part in umbracoSettings.config:

```
```

**Comment by leekelleher** [comment]
Hmmm, I'm not to sure why it'd be throwing a 404 error then. You could try moving the partial-view to the "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/" folder, but the last fallback in the code is to call the partial with the doctype alias.

https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/Extensions/HtmlHelperExtensions.cs#L143

**Comment by bjarnef** [comment]
It seems to fix the issue if I change this value to false.

```disableFindContentByIdPath="false"```

From another project I can see the value is false, which seems to be default value.

**Comment by bjarnef** [comment]
I think the reason it has this set to true, is to prevent from accessing a new, e.g. mysite.com/19654

**Comment by leekelleher** [comment]
It's the first I'd heard about the `disableFindContentByIdPath` option.  Of course, this is a showstopper for DTGE! 😖 

I'll close this ticket off, and open a new one specifically about `disableFindContentByIdPath`.

Interesting that you and @PerplexDaniel both raised this issue at exactly the same time, (unless if you're working together? 😃)

**Comment by bjarnef** [comment]
@leekelleher no we don't, but apparently we had the same thought 😁

**Comment by PerplexDaniel** [comment]
Haha, that is indeed quite a coincidence :-) Thanks for your fast response Lee.
