### ISSUE TITLE
Umbraco's disableFindContentByIdPath set to true, breaks DTGE preview

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-doc-type-grid-editor#109]
Umbraco, _(update: v7.2.5)_, introduced an option `disableFindContentByIdPath` (which is `false` by default). If this is set to `true`, then DTGE preview functionality will not work.

The preview mechanism needs to be refactored.  An effort was made in PR #105, but needs further development work.  The latest code is currently available in the [`feature/preview-unpublished`](https://github.com/umco/umbraco-doc-type-grid-editor/tree/feature/preview-unpublished) branch.

There are a some complications with the current refactoring, in that it can break backwards-compatibility, _(which we'd like to avoid)_.

Marking this as **up-for-grabs**, as my current work projects aren't using DTGE, and my free (personal) time is limited.

**Comment by PerplexDaniel** [comment]
For some more context, `disableFindContentByIdPath` seems to have been introduced in [this commit, March 24, 2015](https://github.com/umbraco/Umbraco-CMS/commit/9dfccd86fd3961712be529042941c2a62f7c6bb8#diff-ca429c093e231c5d6ea51afdbb5d2044) so it's actually quite old.

**Comment by leekelleher** [comment]
Wow, v7.2.5! Weird that I hadn't heard about it.  Thanks for finding the commit. 👍

**Comment by leekelleher** [comment]
Closing this ticket, the preview mechanism has been refactored with PR #111.
Due in upcoming v0.6.0-beta release.

_We'll be looking for beta testers to make ensure they're happy with their existing implementions before doing a full release._
