### ISSUE TITLE
Preview is incompatible with Content Templates (blueprints)

### ISSUE THREAD

**Issue by skidmow** [umco/umbraco-doc-type-grid-editor#113]
I have a Content Template (previously blueprints) that contains a Grid, with DTGE properties associated.

As I understand it from reading the previous issues, DTGE preview does not support unpublished nodes. Content Templates are unpublished by design, as they are not content nodes, they are templated blueprints that are pre-populated with data. Therefore when editing the Content Template, it always fires errors like this:

Unauthorized access to URL: 
/Cms/
with data: 
"id=d0896009-bed8-e4b6-99d6-004c877deeea&
editorAlias=scriptContainer&
contentTypeAlias=textBox&
value=%7B%22name%22%3A%22Script+Container%22%2C%22content%22%3A%22This+is+a+test%22%7D&viewPath=%2Fcms%2FViews%2FPartials%2FGrid%2FEditors%2FDocTypeGridEditor%2F&
previewViewPath="
Contact your administrator for information.

I can disable preview in DTGE to avoid these errors, but I would like to still have the ability to preview on the actual published content nodes. Disabling it would remove that capability.

Any ideas on a workaround?

**Comment by leekelleher** [comment]
Ooooo, would you mind giving the latest beta version a try please? Thanks!

https://github.com/umco/umbraco-doc-type-grid-editor/releases/tag/0.6.0-beta
