### ISSUE TITLE
localization feature in 0.6.0-beta requires at least Umbraco 7.6

### ISSUE THREAD

**Issue by skttl** [umco/umbraco-doc-type-grid-editor#115]
This is because `localizeMany` is used in https://github.com/umco/umbraco-doc-type-grid-editor/blob/e8d128d5b39c44be676743fefd3ab2fce18c1ca2/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js#L31

`localizeMany` was added in Umbraco 7.6.

**Comment by leekelleher** [comment]
Thanks for following up on this one @skttl!

We'll review what to do with it... my initial feeling is to bump up the minimum Umbraco dependency to v7.6 - since we've had **6 minor version** releases since then, (v7.12.x) 😃

**Comment by leekelleher** [comment]
Bumped up the Umbraco dependency to v7.6.0 in commit 591cc4d386a9c0937e4d31d8b0c43cda856b432e
Thanks for spotting this @skttl!
