### ISSUE TITLE
Name template doesn't seem to have any effect

### ISSUE THREAD

**Issue by SteveEdson** [umco/umbraco-doc-type-grid-editor#116]
We use a lot of doc type aliases in a single grid editor config item, when we use the "reorder" option, each grid item has the name of the category, making it difficult to see what component has been used where (see screenshot below), ideally we would like this to use the name of the doc type instead.

The config we have is

```js
    {
        "name": "Partials",
        "alias": "partials",
        "view": "~/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
        "render": "~/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
        "icon": "icon-layout",
        "config": {
            "allowedDocTypes": ["dotDivider", "pdfViewer", "subNav", "documentLink", "quickLinks", "sectionTitle"],
            "enablePreview": true,
            "viewPath": "~/Views/Partials/Grid/Editors/DocTypeGridEditors/",
            "previewViewPath": "~/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews",
            "previewCssFilePath": "~/cmsassets/assets/css/umbraco-admin.css",
            "previewJsPath": "~/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/dtge.js"
        }
    },
```

However setting a `nameTemplate` value doesn't have any effect either. (We've tried different variable names, as well as hard coding a value e.g. "{{title}}" and "Test123"). 

In issue https://github.com/umco/umbraco-doc-type-grid-editor/issues/14#issuecomment-160315537 it was suggested that:

> "it will use the docTypeAlias be deafault, but you can override this be either a) having a property with the alias "name" on your doc type, or b) configuring a "nameTemplate" in the editor config file"

however this doesn't seem to be the case.

We are using v0.5.0

![image](https://user-images.githubusercontent.com/1201960/46362681-df4c0600-c668-11e8-9eb4-b8db0d7db596.png)

Any help on this one would be massively appreciated.

Thanks

**Comment by SteveEdson** [comment]
Thanks for the update. 

Is there any chance we could come with a backwards compatible solution and submit a PR to get it merged back in the core? Then we don't have to worry about future updates, and I think this could be useful for other people too.

Thanks

**Comment by leekelleher** [comment]
@SteveEdson Yes, we're totally open for any enhancements!

**Comment by SteveEdson** [comment]
@leekelleher I have a half working solution, but when I update $scope.control.editor.name, it's also changing the name of the doctypegrideditor type in the "Choose type of content" dialog. 

Is there anything I can do to change this, such as an event when that dialog is opened, or a separate value in the template etc?

Thanks

**Comment by SteveEdson** [comment]
@leekelleher think I might have hit a stumbling block with this, changing the value of `$scope.control.editor.name` seems to change the name of the DTGE editor in general for that group of doc types, so editing one of the components updates the names of all the others, as well as the issue mentioned above.

I'm not sure if there is any way around this, since I'm assuming that part is managed by Umbraco's grid and just uses `$scope.control.editor.name` to get the name for it?

**Comment by leekelleher** [comment]
@SteveEdson How's that for timing, I was just writing a reply saying pretty much the same thing.

I'm sure there'll be a way to hack around this, but it would be hacky... which we probably wouldn't want in DTGE itself.

I've been looking if there's a way to get the grid cell's parent-previous-sibling, (class of `umb-control-collapsed`) and modifying the innerText.  Like I say, hacky as hell.

**Comment by leekelleher** [comment]
@SteveEdson I've figured out a hacky way of doing it 😄 

In the main ("Our.Umbraco.DocTypeGridEditor.GridEditors.DocTypeGridEditor") controller, include the `$element` parameter, _(note, don't forget to use DI),_ then in the `$scope.setPreview` function (around line 115-ish), add this line...

```js
$element.closest(".umb-control").find(".umb-control-collapsed").text(model.dtgeContentTypeAlias);
// or this if you wanna go pure DOM? try this...
// $element[0].parentNode.parentNode.previousElementSibling.innerText = model.dtgeContentTypeAlias;
```

Like I say it's a hack, as it's kinda taboo to manipulate the DOM from an AngularJS controller. 🙄

**Comment by SteveEdson** [comment]
@leekelleher thanks, agreed it's a bit hacky but it might get the job done for the time being. I don't think there's a cleaner way to do this, without making changes to Umbraco itself which seems like a stretch.

Thanks for the help!

**Comment by leekelleher** [comment]
Thanks @SteveEdson, yeah it's a shame there isn't a cleaner way to do this.

I'll close this ticket off.
