### ISSUE TITLE
V8 Support

### ISSUE THREAD

**Issue by cleversolutions** [umco/umbraco-doc-type-grid-editor#126]
I'm not sure if this is a bug in v8 preventing loading of package dlls, or if support for v8 has to be added to DTGE. Using the latest nightly build of V8 (v8.0.0-alpha.58.1500) DTGE doesn't show up in the v8 package list, and adding it via nuget blows a sad YSOD.
```
Boot failed: Umbraco cannot run. Sad. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Reflection.ReflectionTypeLoadException: Could not load all types from "Our.Umbraco.DocTypeGridEditor, Version=0.6.6921.29169, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.ApplicationEventHandler: Could not load type 'Umbraco.Core.ApplicationEventHandler' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.Models.IPublishedContent: Could not load type 'Umbraco.Core.Models.IPublishedContent' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.ObjectResolution.SingleObjectResolverBase`2: Could not load type 'Umbraco.Core.ObjectResolution.SingleObjectResolverBase`2' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
. System.IO.FileNotFoundException: Could not load file or assembly 'umbraco, Version=1.0.6331.7975, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'umbraco, Version=1.0.6331.7975, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'umbraco, Version=1.0.6331.7975, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'interfaces, Version=1.0.6331.7963, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.IO.FileNotFoundException: Could not load file or assembly 'umbraco, Version=1.0.6331.7975, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.TypeLoadException on Umbraco.Core.Models.IPublishedProperty: Could not load type 'Umbraco.Core.Models.IPublishedProperty' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
. System.IO.FileNotFoundException: Could not load file or assembly 'umbraco, Version=1.0.6331.7975, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
. System.TypeLoadException on Umbraco.Core.Models.IPublishedProperty: Could not load type 'Umbraco.Core.Models.IPublishedProperty' from assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by mattbrailsford** [comment]
DTGE won't be supporting v8 as v8 should be introducing a new and improved grid that makes DTGE redundant.

**Comment by cleversolutions** [comment]
Thanks @mattbrailsford, that's very exciting.

**Comment by mattbrailsford** [comment]
Sure is. I don't know how far along it is, but the new grid should treat all cells as `IPublishedContent` blocks, like Nested Content does. In this sense it makes DTGE redundant and also makes the grid way more powerful. We've been waiting for this for a long time so nice to see it finally becoming reality.

**Comment by dawoe** [comment]
Hi @mattbrailsford 

I don't think much work has been done on the new grid since last codegarden : https://github.com/umbraco/Umbraco-CMS/tree/temp8-grid2

So if you have any other information, I don't think we will see a new grid in the first release of V8.

Would be nice to see a version of DTGE that supports of V8. Maybe @warrenbuckley can have a stab 😄

**Comment by mattbrailsford** [comment]
Then my suggestion would be to push back to HQ to get the grid2 finished. 

If someone wants to submit a PR, that's cool, but untill there is confirmation that grid2 is being put on the back burner, it's not something we are looking to port over.

**Comment by cleversolutions** [comment]
@nul800sebastiaan mentioned over at https://github.com/umbraco/Umbraco-CMS/issues/3817 that grid 2 won't make it to 8.0.0. Sad.

**Comment by dawoe** [comment]
`.... but untill there is confirmation that grid2 is being put on the back burner ....`

The branch for grid2 has not seen any activity since the CG retreat... i don't think it has high priority at the moment in HQ.

Will see if I can find a stab on upgrading after I have done my own packages. 

Dave

**Comment by dawoe** [comment]
Hey @leekelleher and @mattbrailsford 

You guys outlined you are not going to do the V8 version in favor of Grid V2...or whatever it is being called now.

Problem is that it is still in RFC fase now. So it will take a while before we see anything useable in core. But our editors need a block building experience in V8  now.

So what are the plans for the PR @skttl is working on (#137 ). Are you guys going to merge it?

Maybe DTGE can be moved to https://github.com/umbraco-community if you are not planning on doing the V8 port release.

Dave

**Comment by leekelleher** [comment]
@dawoe I'm totally aware of the effort being put into PR #137, (@skttl has been doing an magnificent job! 🌟). It's only unfortunate that some folk feel we've been silent on the matter, _(where as I spoke to many people at CG19 about this)_. I feel there's a difference between giving people space to do their thing vs sticking one's oar in.

As for merging #137 in, @skttl hasn't mentioned (to me specifically) that the PR is ready yet.

re: 'umbraco-community' org, I'm not sure what problem that would solve? Unless if we're talking about ongoing support? Then yes, that's a very good question, which I'm sure even @skttl would have input on, _(e.g. this isn't just mine or @mattbrailsford's decision)_. 🤔

**Comment by skttl** [comment]
PR is still a draft, but I think we are really close now. I hope someone can look it over, and comment on the last todos, then we should be pretty much good to go.

I'll be happy to continue support for this, at least until the new block based editors drop (expecting in the next 3-6 months). But it would probably be bug fixing only.

**Comment by dawoe** [comment]
Hi @leekelleher 

I just raised the question to see if you guys were planning to eventually accept the PR. I didn't get the chance to chat with you properly at CG this year, so I don't know what your plans are with DTGE. Mainly because you did not react on the PR yet.

Earlier you guys said you were not going to support V8 with DTGE because of Grid V2 coming. So that's why I suggested the move to umbraco-community. So it can be picked up by the interested community members. 

@skttl keep up the amazing work. From experience I know what pain it is to upgrade packages to V8

**Comment by skttl** [comment]
@dawoe only pain was from my own stupid mistake in the valueconverter, learning new stuff is fun :)

**Comment by jesperordrup** [comment]
> PR is still a draft, but I think we are really close now. I hope someone can look it over, and comment on the last todos, then we should be pretty much good to go.
> 
> I'll be happy to continue support for this, at least until the new block based editors drop (expecting in the next 3-6 months). But it would probably be bug fixing only.

@skttl 
Just did a test implementation and it looks really good. Are there any known bugs? #h5yr

@leekelleher 
Any plans for accepting PR or other plans? #h5yr2 ;-)

**Comment by jesperordrup** [comment]
Just read the:
https://github.com/umbraco/rfcs/pull/11

Something great will come out of the RFC as it seems to aim high solving everything :-D 
I assume that it will be a long while before we see a release of a "grid v2" 

I think there is a need for DTGE for V8 now and for a long time after "grid v2". 

Here's me hoping that either this PR will be accepted or a fork of DTGE for V8 will be created or something third will happen. If I can help in any way - let me know.

**Comment by cleversolutions** [comment]
@jesperordrup I think your right about DTGE being used for years to come. Even when grid V2 drops, I would expect there to be a lot of sites out there with both legacy grid V1 pages, and new grid V2 pages.
