### ISSUE TITLE
Panel closes if a toggle label is clicked

### ISSUE THREAD

**Issue by StefanoChiodino** [umco/umbraco-doc-type-grid-editor#133]
Umbraco v7.13.1
DTGE v0.6.1

![image](https://user-images.githubusercontent.com/1428893/51834533-862c7000-22f2-11e9-9a33-8c0641431ad9.png)

Clicking on the label of a checkbox closes the side panel instead of toggling the field value.

No error in the console.

**Comment by leekelleher** [comment]
Thanks for raising this @StefanoChiodino.

Interestingly I've just closed off another ticket with a similar issue, https://github.com/umco/umbraco-doc-type-grid-editor/issues/132#issuecomment-458101426

The issue itself it with Umbraco, specifically the updates to the "True/False" (Checkbox) property-editor. It's not something that we can fix within DTGE.  See issue #95 for similar issue and explanations.

**Comment by StefanoChiodino** [comment]
Thank you very much @leekelleher 👍
