### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by ande4559** [umco/umbraco-doc-type-grid-editor#142]
Hello guys

It is not possible for me to install your package anymore. 
When i use the nuget installer it gives me this error: 

```
Severity Code Description Project File Line Suppression State Error
Exception 'System.AggregateException' thrown when trying to add source 'https://nexus.odknet.dk/repository/nuget-group'. Please verify all your online package sources are available.
One or more errors occurred.
Unable to load the service index for source https://nexus.odknet.dk/repository/nuget-group.
An error occurred while sending the request.
The remote name could not be resolved: 'nexus.odknet.dk'				

```

Have you removed it entirely until you upgrade(if you upgrade) to Umbraco V8?
I was using this package alot before.  So could be nice to hear alternatives or information about what your decision on this package is.

Yours sincerely 
Anders

**Comment by leekelleher** [comment]
@ande4559 This error doesn't seem to be an issue with DTGE, rather with the NuGet repo at `https://nexus.odknet.dk/repository/nuget-group`?

The NuGet package for DTGE is available from here: <https://www.nuget.org/packages/Our.Umbraco.DocTypeGridEditor/>

re: Umbraco v8 - ticket #130 has the latest information.

**Comment by ande4559** [comment]
![image](https://user-images.githubusercontent.com/31615453/58424183-2c1c9b00-8097-11e9-8bab-c94db1ebbacd.png)
 still gets this error when i install

**Comment by leekelleher** [comment]
Hi @ande4559. This error is specifically to do with the NuGet repository at `https://nexus.odknet.dk/repository/nuget-group`.  The error message literally says `"Please verify all your online package sources are available."` ... and `"The remove name could not be resolved: ''nexus.odknet.dk"`, which suggests that domain isn't accessible (on your machine or network or anywhere).

I'm closing this ticket off, as it is nothing to do with DTGE itself.

**Comment by ande4559** [comment]
Yes i see, it was because it only took from my vpn connection for some reason.. very weird. Thank you for the quick response.
