### ISSUE TITLE
Take into account that doctypes names/property names and property descriptions can be localized

### ISSUE THREAD

**Issue by TimGeyssens** [umco/umbraco-doc-type-grid-editor#60]
Since In Umbraco you can localize the backoffice but if you then use doc type grid editor you end up with the keys instead of the localized values

**Comment by TimGeyssens** [comment]
Ok think I got it working, will send over a pull request, just checking if there are other places where some static values need to go into a lang file

**Comment by leekelleher** [comment]
Cool, thanks @TimGeyssens, look forward to seeing the PR! #h5yr

**Comment by leekelleher** [comment]
I believe this has been fixed in PR #90
