### ISSUE TITLE
Doesn't work by default with Skybrud.Umbraco.GridData

### ISSUE THREAD

**Issue by HarveyWilliams** [umco/umbraco-doc-type-grid-editor#61]
Someone briefly mentioned the use of using Skybrud GridData with DTGE: https://github.com/umco/umbraco-doc-type-grid-editor/issues/44#issuecomment-252553870

But they don't seem to mention any problems.

I found that I got this casting error:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Skybrud.Umbraco.GridData.GridControl' does not contain a definition for 'value'
```

However, updating `DocTypeGridEditor.cshtml` to this fixed the error:

```
@using System.Web.Mvc
@using System.Web.Mvc.Html
@using Skybrud.Umbraco.GridData
@using Microsoft.CSharp.RuntimeBinder
@using Our.Umbraco.DocTypeGridEditor.Helpers
@using Our.Umbraco.DocTypeGridEditor.Web.Extensions
@inherits Umbraco.Web.Mvc.UmbracoViewPage<GridControl>
@{ 
    var model = (dynamic)Model.JObject;
}
@if (model.value != null)
{
    string id = model.value.id.ToString();
    string editorAlias = model.editor.alias.ToString();
    string contentTypeAlias = "";
    string value = model.value.value.ToString();
    string viewPath = model.editor.config.viewPath.ToString();

    try
    {
        contentTypeAlias = model.value.dtgeContentTypeAlias.ToString();
    }
    catch (RuntimeBinderException)
    {
        contentTypeAlias = model.value.docType.ToString();
    }

    if (contentTypeAlias != "")
    {
        var content = DocTypeGridEditorHelper.ConvertValueToContent(id, contentTypeAlias, value);

        @Html.RenderDocTypeGridEditorItem(content, editorAlias, viewPath)
    }
}
```

I don't expect DTGE to work by default with GridData, but it would be great if there was some documentation on the issue and how to fix it - I'm not sure if my above solution is the best.

**Comment by leekelleher** [comment]
@HarveyWilliams Thanks for raising this, and posting your solution.

I haven't used Skybrud's GridData package, so not really sure what to suggest about this.
As you say, from DTGE's perspective, it shouldn't really need to be aware of the `GridData` view-model.  My feeling is that `GridData` should (somehow) accommodate DTGE's data/value.

**Comment by naepalm** [comment]
@HarveyWilliams Thanks for this! Your solution fixed my issue right up as well. Really appreciate you posting this :)

**Comment by mattbrailsford** [comment]
This really needs reporting here
https://github.com/skybrud/Skybrud.Umbraco.GridData/issues

GridData is clearly not passing in the same value that standard Umbraco is
so it needs to convert it back if it's not an editor it understands.

**Comment by leekelleher** [comment]
Closing this ticket, I agree with @mattbrailsford - it's an issue/concern for the Skybrud GridData package.

Just to note, we're totally happy to discuss any generic changes/improvements with DTGE... Umbraco 3rd-party package interoperability is a deeply un-explored area.
