### ISSUE TITLE
GetContentTypes 404

### ISSUE THREAD

**Issue by meregan** [umco/umbraco-doc-type-grid-editor#64]
Hi

Firstly, this plugin is the best, love it, problem is I can't always get it to work.

The error I am getting currently on 7.5.8 is as follows:

After install when and adding Doc Type as an editor to my grids i go to the content select the doc type as and editor and get the following error:

Request error: The URL returned a 404 (not found): 
/umbraco/backoffice/DocTypeGridEditorApi/DocTypeGridEditorApi/GetContentTypes

On some installations it works fine and some it doesn't. I have compared installations, permissions and can't see what the difference is.

Help appreciated!

Am i missing something?

**Comment by cherylcarpenter** [comment]
+1  Works great until i try to create same page on another server. same config, same permissions, 0 diff. It won't see my view path or pull in the fields.

**Comment by leekelleher** [comment]
I haven't been able to reproduce the 404 error yet.  Which version of DTGE are you using? (I'm assuming the latest, v0.3.0?)

**Comment by meregan** [comment]
It was v0.3.0, I solved the issue purely by copying the config from a working version, I think I started by using the config from the documentation.

**Comment by leekelleher** [comment]
@meregan Thanks for the heads up about the documentation, we'll review it - make sure it's up to date.

**Comment by leekelleher** [comment]
Closing the issue for now. @meregan I haven't been able to reproduce this issue - the current documentation is up to date. Please feel free to reopen if needed.

**Comment by meregan** [comment]
You back from holiday then?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leekelleher** [comment]
@meregan - not holiday, just a busy few months - moved house, heavy deadlines with work - umbraco packages were put on the back-burner 😄

**Comment by meregan** [comment]
Well we appreciate your hard work, thanks Lee we love you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leekelleher** [comment]
Why thank you @meregan! #h5yr
