### ISSUE TITLE
Save issue

### ISSUE THREAD

**Issue by Kimtho** [umco/umbraco-doc-type-grid-editor#65]
Hi 
I have a issue where the first save click reset the content. 
https://www.heyday.dk/files/2017-01-19_1323.swf

**Comment by leekelleher** [comment]
Hi @Kimtho, from looking at your screencapture, it appears that the DTGE panel is opened multiple times (I can tell from the darkness of the panel's shadow on the left hand side).

Then when you click the Save button, the panel is saved/closed, but another underlying panel is there (containing the original content).

---

@mattbrailsford The issue could be that clicking on the DTGE preview area multiple times might open multiple panels?

**Comment by Kimtho** [comment]
aaah thats the issue, thanks :) had a customer that double clicked on it. Could not recreate the issue :p

**Comment by garpunkal** [comment]
I have the same issue on a sandbox application. 
https://github.com/garpunkal/GridEditorSandbox

If you click multiple times on the Grid Editor component it opens multiple frames, causes the "save" issue described above. 

I've got the following property editors on my document type, string, media picker, mntp, rte, slider. 

Not sure if this helps, but I can definitely see the issue happening.

**Comment by leekelleher** [comment]
With PR #86, the old dialog service has been replaced with Umbraco's umb-overlay directive.
I've tried to reproduce this issue - of quick multiple clicks to open the panel, and it appears to no longer be an issue.

Closing this issue.
