### ISSUE TITLE
DocTypeGridEditorSurfaceController

### ISSUE THREAD

**Issue by meregan** [umco/umbraco-doc-type-grid-editor#66]
While creating a controller with doctype alias and an action alias that contains the documentation suggestion:

  // Do your thing...
         return CurrentPartialView();

Anything else means the controller isn't called even simple stuff like var x = 1;

anyone got the custom controllers to work other thank just doing a return?

**Comment by leekelleher** [comment]
@meregan I've been using custom controllers for DTGE cells without issue.  Would you be able to provide a code snippet of your controller?

Just to note, if you are changing your view-model, then you will need to pass it to the `CurrentPartialView(model)` method call.

**Comment by meregan** [comment]
Hi Lee, know you are busy so downloaded the source and using that to troubleshoot, get back to you when i fix it.

**Comment by leekelleher** [comment]
@meregan Cool, thanks! 👍

**Comment by leekelleher** [comment]
Closing the issue for now. @meregan please feel free to reopen if needed.
