### ISSUE TITLE
Allowed Doc Types naming issue in grid.editors.config.js

### ISSUE THREAD

**Issue by xman51** [umco/umbraco-doc-type-grid-editor#73]
I have two doc types whose aliases are "map" and "sitemap". In the gird.editor.config.js file, I have the following configuration:

```
{
    "name": "Doc Type",
    "alias": "docType",
    "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
    "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
    "icon": "icon-item-arrangement",
    "config": {
      "allowedDocTypes": ["video", "titleAndDocumentList", "map", "parkNRideLocation", "wifiPasswordImage", "nestedZones"],
      "nameTemplate": "",
      "enablePreview": true,
      "viewPath": "/Views/Partials/",
      "previewViewPath": "/Views/Partials/",
      "previewCssFilePath": "",
      "previewJsFilePath": ""
    }
  }
```
Notice that the allowedDocTypes does not include "sitemap" however sitemap is showing up in the list of doctypes allowed in my grid. I think this is because the text "map" is part of the alias "site**map**".

Unfortunately, the only way I can currently fix is just not possible at the moment as I would have to rename the alias. This would take a lot of time to fix. Was hoping you can fix in the next update. Thanks :)

**Comment by leekelleher** [comment]
@xman51 You're right, DTGE is performing a regex match on the doctype alias, (for reference: [`DocTypeGridEditorApiController.cs#L29`](https://github.com/umco/umbraco-doc-type-grid-editor/blob/master/src/Our.Umbraco.DocTypeGridEditor/Web/Controllers/DocTypeGridEditorApiController.cs#L29))

Our current recommendation would be to use `"^map"` as that regex would be explicit to match your doctype alias.

**Comment by mattbrailsford** [comment]
You should probably make it `^map$` to be totally explicit. 

We use regex to allow things like `*Widget$` style configs to automatically support doc types with a prefix without having to add them manually every time.

**Comment by xman51** [comment]
@leekelleher  Thank you so much. using the caret worked like a charm! :)

**Comment by mattbrailsford** [comment]
@xman51 aces, glad it's working. Just to add to my reply, if you do only go with `^map` be aware if you had a doc type of say `mapleSyrup`, this would appear in the list. `^bla` is essentially saying "starts with", where as `^bla$` is saying, "must be bla exactly". Just to be aware, in case you need a "mapleSyrup" doctype :D

**Comment by leekelleher** [comment]
...but let's face it, who doesn't want that "mapleSyrup" doctype?
