### ISSUE TITLE
?dtgePreview=1 post 404

### ISSUE THREAD

**Issue by digbyswift** [umco/umbraco-doc-type-grid-editor#75]
I have a standard 0.4.0 nuget install in Umbraco v7.6.1 (.Net 4.6.2) and I'm getting the following error message when I load a page where I have added a doc type.

![grid-editor-404](https://cloud.githubusercontent.com/assets/1391597/26630910/ac039932-4600-11e7-8dea-b7f7f4e04a8c.PNG)

The config is:

```
{
	"name": "Content picker",
	"alias": "docType",
	"view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
	"render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
	"icon": "icon-item-arrangement",
	"config": {
		"allowedDocTypes": ["GridWidget$"],
		"nameTemplate": "",
		"enablePreview": true,
		"viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
		"previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
		"previewCssFilePath": "",
		"previewJsFilePath": ""
	}
}
```

I have created a doc type called "Basic Content Grid Widget" (alias of "basicContentGridWidget") and I have a file at both /Views/Partials/Grid/Editors/DocTypeGridEditor/BasicContentGridWidget.cshtml and /Views/Partials/Grid/Editors/DocTypeGridEditor/Preview/BasicContentGridWidget.cshtml

When the page in the CMS loads, there is no preview and I can see from my proxying tool that the following POST request is returning a 404:

http://localhost:56529/1196?dtgePreview=1

**Comment by leekelleher** [comment]
@digbyswift - thanks for raising this. Does your website have any published nodes?

Currently DTGE's preview mechanism requires at least the homepage to be published.  It's not ideal, but at the time when we developed DTGE, it was the only option.

**Comment by digbyswift** [comment]
All of the nodes are published. However the root node (which is an immediate parent of the current node) is a document type without a template which performs an internal redirect to a homepage node. Could it be this root node?

**Comment by leekelleher** [comment]
@digbyswift Yes, that'll be it.

I've experienced that problem too, [which led me to add in a check for `RedirectResult`](https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/Attributes/DocTypeGridEditorPreviewAttribute.cs#L23).  Then in my controller code for the homepage redirect, I ended up adding in a check if it was a DTGE preview request.

```csharp
if (Request.QueryString["dtgePreview"] == "1" && Request.HttpMethod == "POST" && Request.QueryString["nodeId"] != null)
{
    return View(model);
}
```
I know it's not ideal, but again it's due to how the preview mechanism currently works.  (_I'd love to rewrite it!_ #59)

**Comment by digbyswift** [comment]
So just to be sure, I've recreated the content structure but with a new node at the root which has a template. I have also removed the redirect property from the root. I've then republished all the content. However, unfortunately the child nodes are still all displaying the same error as before and the preview is still not displaying. I've rolled the client dependency and restarted the app too.

**Comment by digbyswift** [comment]
Ok, I have fixed the error but not the previews not displaying. The error was caused because I had set web.routing > disableFindContentByIdPath=true in the umbracoSettings.config as part of my default setup.

Is there any reason why the previews would not be displaying?

**Comment by leekelleher** [comment]
@digbyswift Cool that you've resolved it.

Hopefully one day soon I can rewrite the preview mechanism! 😃

**Comment by digbyswift** [comment]
It's the first time I've used it and _nearly_ gave up but now that I've got it working, it looks real good. Thanks for your help and time!
