### ISSUE TITLE
Rendering preview is not working when item is not published

### ISSUE THREAD

**Issue by cmwalolo** [umco/umbraco-doc-type-grid-editor#76]
The url used to rendering a preview of an unpublished page is 
http://domain/?dtgePreview=1&nodeId=1949 which results to a redirect ?  
If the item is published http://domain/1949?dtgePreview=1 is working. 

Do we miss something in the Actionfilters or in the setup ?

**Comment by leekelleher** [comment]
@cmwalolo Which version are you using, the latest, v0.4.0?

The preview doesn't really work with unpublished pages - it's a flaw in the preview mechanism, (we'd love to rewrite it, _if we had the time_).  We did add a fix in v0.4.0 to prevent it falling over if the unpublished page tries to redirect.

**Comment by cmwalolo** [comment]
Hi, 

0.3.0.  I guess we should already start with the upgrade. Could it be solved by launching the rendering in preview mode as it does with the "Preview button" on the item ?

**Comment by leekelleher** [comment]
Closing this specific ticket.  The issue still remains, but want to combine it with ticket #59 - for an overhaul of the preview mechanism.
