### ISSUE TITLE
Reordering Custom Doc Type Editors on a page not allowed

### ISSUE THREAD

**Issue by nkleroux** [umco/umbraco-doc-type-grid-editor#81]
Unable to order custom doc type editors (Custom overridden LeBlender controllers). Information and details on recreating the issue can be found here:
[https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/75665-reordering-doc-type-editors-on-a-page-not-allowed]

**Comment by nkleroux** [comment]
For some reason the grid layout data type did not want to save mu option to include all editors. Had to create new one and transfer existing widgets / editors over.

**Comment by leekelleher** [comment]
Hi @nkleroux - I haven't experienced this myself - but I never used the LeBlender, so not sure what complications that may bring to it?  Glad to hear that you've been able to resolve it. 😃
