### ISSUE TITLE
Guids are updated everytime the DTE content is saved

### ISSUE THREAD

**Issue by simonech** [umco/umbraco-doc-type-grid-editor#82]
Each DTE controls have its own id (as guid) but this guid is renewed everytime the cell is edited.
It should be created the first time and then just moved around

**Comment by simonech** [comment]
Basically, the DTE js plugin is resetting the guid everytime the side panel with the document is saved.
There is check in the code, but it doesn't work.

            if (!("id" in $scope.control.value) || $scope.control.value.id == "") {
                $scope.control.value.id = guid();
            }

The problem is that the id is not sent to the dialog and back when saved.


In the doctypegrideditor.controllers.js there is the function that opens the side panel and handles the callback when the panel is closed.  It was missing the setting of the guid.

I did some quick debugging on the google dev tools and I think the solution is this:


        $scope.setDocType = function () {
            dtgeDialogService.open({
                editorName: $scope.control.editor.name,
                allowedDocTypes: $scope.control.editor.config.allowedDocTypes || [],
                nameTemplate: $scope.control.editor.config.nameTemplate,
                dialogData: {
                    id:$scope.control.value.id,
                    docTypeAlias: $scope.control.value.dtgeContentTypeAlias,
                    value: $scope.control.value.value
                },
                callback: function (data) {
                    $scope.setValue({
                        dtgeContentTypeAlias: data.docTypeAlias,
                        value: data.value,
                        id:data.id
                    });
                    $scope.setPreview($scope.control.value);
                }
            });
I'll do some more testing and send a PR

**Comment by leekelleher** [comment]
Cool, thanks @simonech!

**Comment by simonech** [comment]
Sorry, never made it to sent the PR.

**Comment by leekelleher** [comment]
@simonech No worries. I'd (eventually) found some time to give DTGE a little love, so was trying this out and your code (in your comment above) worked, so thank you! 😃
