### ISSUE TITLE
Doc Type Grid Editor in the Core!

### ISSUE THREAD

**Issue by meregan** [umco/umbraco-doc-type-grid-editor#85]
This plugin belongs in the Core!

Vote for Core integration today:

[http://issues.umbraco.org/issue/U4-10890](http://issues.umbraco.org/issue/U4-10890)

Support this plugin and improve your Umbraco.

**Comment by leekelleher** [comment]
Hi @meregan - thanks for the suggest and glowing endorsement! 🎉 

It's really up to the community if they'd like to see DTGE in Umbraco core. I'll close off this ticket here and if anyone would like to vote or discuss further, here are the links where to do that:

- http://issues.umbraco.org/issue/U4-10890
- https://our.umbraco.org/forum/contributing-to-umbraco-cms/90220-doc-type-grid-editor-in-the-core
