### ISSUE TITLE
Could DTGE use Inner Content?

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-doc-type-grid-editor#91]
> For contributor discussion only

**Could be retrofit DTGE to make use of Inner Content?**
@mattbrailsford I guess I'm looking for an initial, _is it technically possible? with maintaining backwards-compatibility?_

With the recent Umbraco v7.8 _non-breaking-breaking-change_, (ref: PR #89) we would only need to maintain it in one place.

**Comment by mattbrailsford** [comment]
Hmm, would need to think. Initially I would say no, because the Grid doesn't recursively call down to DTGE to do "it's thing", but maybe there is a way to do those things linline like we currently do.

Could be worth looking into

**Comment by leekelleher** [comment]
Another one to note is the feature you've just added for unsaved changes, re: https://github.com/umco/umbraco-stacked-content/issues/28 (DTGE issue: #52)

**Comment by leekelleher** [comment]
Closing this idea off.

Due to the nature of the Grid (v1) and DTGE, it'd be a considerable dev effort, which will be rendered useless for v8, (e.g. Grid v2: Super Grid).
