### ISSUE TITLE
Link and media pickers from RTE open slow

### ISSUE THREAD

**Issue by MartijnKooij** [umco/umbraco-doc-type-grid-editor#92]
I hope you can help us out, seems like we found a weird integration issue somewhere in the mix between Umbraco - TinyMCE - DoctypeGridEditor - Custom DataTypes. We have been trying at this for quite a while now but we are running out of ideas.

Here's our setup:
- We have a custom DocType with a Textstring and a Richt text editor property named "MyCustomDocType".
- We have a custom Datatype (using property editor Nested Content) that uses the "MyCustomDocType" as DocType, this datatype is named "NestedMyCustomDocTypes".
- We have a DocType with a single property of our custom datatype "NestedMyCustomDocTypes", this DocType is named "MyCustomDocTypeCollection"
- We have configured the DocTypeGridEditor to use "MyCustomDocTypeCollection" as the only allowedDocTypes as per the developer instructions named "MyCustomDTGE".

Hope you're still with me...

When adding content to a grid using this MyCustomDTGE the sidebar pops up and we can add a new "Nested Content" (which will show the "MyCustomDocType" with its Rich Text Editor.

Now if in the RTE  we click either the "Add Link" or the "Add Media" buttons, we will have to wait 10+ seconds. And that's the issue that we need to fix for our editors...

- Adding links/media in normal RTEs (which are not rendered in the sidebar) works just fine.
- If I click outside of the TinyMCE frame after clicking on the add link/media button it will open instantly.
-If we modify the umbraco.controller.js to add their "blur event code" right after the createLinkPicker and createMediaPicker the problem is also gone (until the next Umbraco update of course because that will overwrite the umbraco.controller.js...)

The weird thing we see is that the "Link browse" sidebar is opened (as in DOM node created) INSIDE "your" sidebar panel. Not sure if that's related but it appears quite weird.
I don't see any JS errors in the console nor any other reason for the delay. The functionality works just fine after the mysterious waiting period.

Do you have any ideas or suggestions?

Kind regards,
Martijn Kooij

**Comment by leekelleher** [comment]
Hi @MartijnKooij, thank you for the detailed report. 👍 

This sounds like the issue reported in #80 (and fixed in #86).  It hasn't been officially released yet, but there are alpha versions available if you wanted to test it out?

- https://ci.appveyor.com/project/UMCO/umbraco-doc-type-grid-editor/build/artifacts
- https://www.myget.org/gallery/umbraco-packages

**Comment by MartijnKooij** [comment]
Thanks, I overlooked that one (because it's closed but not yet released). I can't get the plugin to work with our code at all but I will report that in the other issue.

**Comment by leekelleher** [comment]
Hi @MartijnKooij - would you be able to test the latest release, to see if you are still experiencing this issue?
https://github.com/umco/umbraco-doc-type-grid-editor/releases/tag/0.5.0
Thanks.

**Comment by markglibres** [comment]
hi @leekelleher , we had the same problem and just upgraded to the latest version, but still it takes about 10-20 seconds to load the link and media picker from RTE

**Comment by leekelleher** [comment]
Hi @markglibres - what version of Umbraco are you currently on?

Also, a small sanity check - can you verify that DTGE was upgraded correctly? We've had a few people recently who've only updated the DLL and not the App_Plugin files - which causes all sorts of confusion. Thanks.

**Comment by markglibres** [comment]
Hi @leekelleher , we started with 7.6.1 then upgraded to 7.7.1, (to .2, .3, .4, .5, .6), then the last upgrade was 7.8.1 about a month ago.. we just noticed it though when we were in 7.8.1..  yesterday we upgraded DGTE to the latest one and can see the updated files including the App_Plugins but still seeing the problem.. I then tried to upgrade to the latest Umbraco 7.10.1 but the right sidebar is not showing after the upgrade so I can't test..

**Comment by MartijnKooij** [comment]
Sorry for not replying. We had a deadline to meet so I have unfortunately decided to hack around the issue for now. So I have not yet continued testing using the newer DTGE release.
I have tagged my hack so we will pick it up again when we continue working on this project, but for now I have to leave it as is...

Thanks for the quick replies and good luck @markglibres, I hope you can get it to work.

**Comment by leekelleher** [comment]
Thanks for the update! I'll close this ticket off now.
