### ISSUE TITLE
Property value editing panel empty when certain data types are used

### ISSUE THREAD

**Issue by richarth** [umco/umbraco-doc-type-grid-editor#94]
Updating to version 0.5 of the package has fixed some issues we were having with an Umbraco 7.8.1 site.

There is one issue we are still having and that is when trying to fill in the property values for our document types.  When editing certain document types in the grid or trying to insert certain document types in the grid we get an empty right hand panel where the property values form should be.  We just get the OK and cancel buttons at the bottom of the panel.

Some document types work, it seems to be document types using the following data types where we see the empty panel.  It looks like the following data types are problematic:

- Multinode Tree Picker
- RTE
- Text area
- Multiple media picker

Comparing the empty panel to one that works it looks like the fieldset for `tab in node.tabs` isn't being injected into the panel.

**Comment by leekelleher** [comment]
Hi @richarth - thanks for reporting this.

Firstly, I'd like to rule out any browser caching issues.  Could it be possible that the JS for the older DTGE version is still cached?  I only say this as it caught someone out last week, see here: https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/90730-issues-with-050

**Comment by richarth** [comment]
Hi Lee,

That's understandable, we've had clients with caching issues after upgrading to 7.8.

I'd cleared the /App_Data/cache folder and had the developer tools open in Chrome, which has disable cache checked and tried hard refreshing which didn't help.

After your message I thought I'd see what my browser was returning for the JS to check if it was a caching thing.  I had a look at the output of DependencyHandler.axd and I could see the old JS, so I followed the steps [here](https://www.paulaikman.co.uk/umbracos-dependencyhandler-clientdependency-dependencyhandler-axd/) to clear the ClientDependency cache.

Since clearing the ClientDependency cache the right hand panel no longer appears at all.

**Comment by leekelleher** [comment]
Hi @richarth - just to check, the right-hand panel no longer appears? As in you click the Grid cell and nothing happens?

I'm not sure what to suggest here - from our tests the upgrade has worked (of course this isn't fool-proof), but with no JS console errors, it's tricky to figure out the root cause.

**Comment by richarth** [comment]
Hi,

Yes the right hand panel is no longer appearing.  I've tried this with debug="false" in the web.config as well and it's still a problem.

I'll click add content at the end of a row and the dialog asking me to chose the type of content appears.  I then click Doc Type and a Doc Type grid item is added which says click to insert item.  When I click where it says click to insert item the right hand panel no longer appears.  The cursor is also a text select cursor at that point rather than a click cursor.

If I click to edit existing Doc Type items that were added pre 7.8 then the right hand panel doesn't appear then either.

The only JS console error is `TypeError: $(...).slick is not a function` from `/umbraco/lib/angular/1.1.5/angular.min.js`.  I have a feeling this error may have been there previously though.

If I click on either the module settings icon or the doc type settings icon then the right hand settings panel does appear.

I'll also try this again once we've updated to 7.9.1.

**Comment by richarth** [comment]
Hi Lee,

I've gotten to the bottom of this.  There were four files that weren't updated during the update process using NuGet.  These are:

```
/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.services.js
/App_Plugins/DocTypeGridEditor/views/doctypegrideditor.dialog.html
/App_Plugins/DocTypeGridEditor/views/doctypegrideditor.html
/App_Plugins/DocTypeGridEditor/package.manifest
```

Once I copied over the files from a clean Umbraco install with version 0.5 of the package, everything started working again.

**Comment by leekelleher** [comment]
Thank goodness for that! 😅 Glad to hear that it's working now.

I'll close off this ticket 👍
