### ISSUE TITLE
Fullscreen Overlay

### ISSUE THREAD

**Issue by TomSteer** [umco/umbraco-doc-type-grid-editor#96]
With version 0.4.0 I was overriding the dialog css to make the editor dialog fullscreen to give more real estate when editing. This doesn't seem to be possible with 0.5.0 due to moving to the new Umbraco overlay. I was just wondering whether this would be a good general enhancement and is even possible with the umb-overlay?

Cheers, Tom

**Comment by leekelleher** [comment]
I'd still like to have a "wide" option for the overlay, ([as commented on here](https://github.com/umco/umbraco-doc-type-grid-editor/pull/56#issuecomment-360761753)).  It'd need to be configurable, I wouldn't want to have a wide/fullscreen for all DTGEs.

**Comment by TomSteer** [comment]
I've given this a try just by editing the dtge editor code and although it works most of the time, I think it would be better if it was something that was implemented as an option on the overlay directive. So I've raised a feature request for Umbraco, to see what they think.
http://issues.umbraco.org/issue/U4-11094
Feel free to upvote it. If they think it's a good idea too, then it would probably be quite a simple pull request 👍

**Comment by sniffdk** [comment]
Have you considered [](https://our.umbraco.org/projects/backoffice-extensions/v7-dialog-expander) ? I'm using my own modified version, and it's been working great so far.

**Comment by TomSteer** [comment]
@sniffdk Thanks for the link Mads, looks like it could be useful. However, in this particular case, the overlays quite often need the extra space so could become annoying if they had to keep resizing it.

**Comment by sniffdk** [comment]
Indeed. Should be fairly easy to modify it to be always on. Might be useful to run it separate from dtge though, imho.

**Comment by leekelleher** [comment]
Closing this ticket, (it's _currently_ beyond DTGE's remit).

If Umbraco had support for changing the width of the overlay panel, or going full-width, (as per [#U4-11094](http://issues.umbraco.org/issue/U4-11094)), then DTGE could hook into that.
