### ISSUE TITLE
7.10.x 404 with Tilde after Upgrading to 0.5.0

### ISSUE THREAD

**Issue by naepalm** [umco/umbraco-doc-type-grid-editor#97]
We recently upgraded a client site from 7.5.13 to 7.10.0 and found that they couldn't update content in the Grid when using DTGE - it was displaying an empty panel and no errors in the console/network (I believe this has to do with the Properties/Info tab change, which I know was patched in a more recent release of DTGE). In an attempt to resolve the issue, I upgraded them again to the patched Umbraco version of 7.10.3 as well as upgrading DTGE from 0.3.0 to 0.5.0 and ended up getting a new issue that's throwing a lot of errors in the console and seems to revolve around (from my thoughts in attempting to debug) the umbraco helper that converts the URLs to absolute URLs. Here's what I've got:

![dtge404errors](https://user-images.githubusercontent.com/5713968/39002817-3b158a1c-43ae-11e8-92c1-d121a555b0fb.png)
![dtgeconsoleinfo](https://user-images.githubusercontent.com/5713968/39002818-3b316994-43ae-11e8-9a9a-7321eee9fcbb.png)

As far as I can tell, it's not stripping out the tilde when it's making the call in example locations like this:

```
var url = umbRequestHelper.convertVirtualToAbsolutePath("~/umbraco/backoffice/DocTypeGridEditorApi/DocTypeGridEditorApi/GetContentTypes");
```

Have you heard about this issue from anyone else? Should I "simply" convert that code back to the previous version that calls the URLs like this instead?

```
var url = "/umbraco/backoffice/DocTypeGridEditorApi/DocTypeGridEditorApi/GetContentTypes";
```

**Comment by leekelleher** [comment]
Hi @naepalm - Interestingly a couple of other people raised this today on the forum...

<https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/91647-404-on-getcontenttypeicon-and-4931dtgepreview-1>

But they'd noticed that it wasn't only DTGE.  So I'm not sure if something else has happened in Umbraco core?

**Comment by leekelleher** [comment]
@naepalm Could you test something for me please?

So I'm thinking that Umbraco's `convertVirtualToAbsolutePath` is borked somehow, this line:
https://github.com/umbraco/Umbraco-CMS/blob/release-7.10.3/src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js#L30

If so, then it's looking like it could be the `trimStart` function.

Would you mind entering `String.prototype.trimStart` into your browser's dev console, and see what is returned? It should be the contents of this function:
<https://github.com/umbraco/Umbraco-CMS/blob/release-7.10.3/src/Umbraco.Web.UI.Client/lib/umbraco/Extensions.js#L90-L95>

Thanks, Lee.

**Comment by leekelleher** [comment]
You know what, it's looking like `trimStart` was added in Chrome 66.
https://www.chromestatus.com/feature/4790066333351936

I'm still on Chrome 65 (upgrading as I type) ... so I suspect that I'm going to experience the same issue very soon. Let's see what happens.

**Comment by naepalm** [comment]
@leekelleher Yeah, definitely something not working right in there:

```
('~/umbraco/backoffice/DocTypeGridEditorApi/DocTypeGridEditorApi/GetContentTypes').trimStart('~')
"~/umbraco/backoffice/DocTypeGridEditorApi/DocTypeGridEditorApi/GetContentTypes"
('~/umbraco/backoffice/DocTypeGridEditorApi/DocTypeGridEditorApi/GetContentTypes').startsWith('~')
true
```

![startswith](https://user-images.githubusercontent.com/5713968/39005960-709f0c78-43b6-11e8-9f0c-be0ef27b039e.png)

**Comment by naepalm** [comment]
@leekelleher I'm running Chrome 66, too, to help!

**Comment by leekelleher** [comment]
@naepalm OK, looks like we're getting close to pinpointing it.  If you enter `"".trimStart` into your dev console, what does that return?

**Comment by naepalm** [comment]
@leekelleher:

```js
ƒ trimStart() { [native code] }
```

**Comment by leekelleher** [comment]
@naepalm Gah, that's rubbish ... so Chrome 66's `trimStart` function doesn't actually trim the start of a string, and Umbraco's polyfill for it isn't being loaded (since it is now native code in Chrome).

![facepalm](https://media.giphy.com/media/14aUO0Mf7dWDXW/giphy-downsized.gif)

**Comment by naepalm** [comment]
@leekelleher Whyyyyyyyyyyyy do people not consider backwards compatibility?! 😭

**Comment by leekelleher** [comment]
Currently, your best bet is to hack the `umbRequestHelper.convertVirtualToAbsolutePath` function in Umbraco (or find a non-hacky elegant way? 🙀), get rid of the `trimStart` and use `substring(2)` directly.

https://github.com/umbraco/Umbraco-CMS/blob/release-7.10.3/src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js#L30

**Comment by leekelleher** [comment]
The wider issue is that `trimStart` is used in several places in Umbraco core:
<https://github.com/umbraco/Umbraco-CMS/search?l=JavaScript&q=trimStart>

**Comment by naepalm** [comment]
Yikes, that's definitely a problem. I can't really have my client unable to work in it until Umbraco patches the problem, so I think that a hack is what I'm going to have to do right now. Are you going to raise an issue on Core or should I go pop one up?

**Comment by leekelleher** [comment]
@naepalm If you could raise an issue that'd be great, (my work day is over for today - family duties call) Otherwise I can raise tomorrow. Thanks.

I'll close this ticket off, as it's not a DTGE issue directly.

**Comment by leekelleher** [comment]
Thank you - nicely described, superstar!

**Comment by ashkansiroos** [comment]
Thanks @naepalm and @leekelleher
