### ISSUE TITLE
Preview doesn't work in combo with UmbMapper

### ISSUE THREAD

**Issue by TimGeyssens** [umco/umbraco-doc-type-grid-editor#98]
On a current project we are using https://github.com/JimBobSquarePants/UmbMapper but it seems when using it dtge has problems rendering the previews. Getting these type of errors:

Cannot bind source type Project.RenderModels.RenderPage`1[[Project.Models.Pages.StandardPage, Project, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] to model type Umbraco.Core.Models.IPublishedContent.

Any ideas on how to update the preview mechanism to make this possible?

**Comment by mattbrailsford** [comment]
What does your preview view look like?

**Comment by TimGeyssens** [comment]
View: 
`@inherits UmbracoViewPage<RenderWidget<WidgetAfbeeldingTekstLink>>


<img src="@Model.Content.Image.Url"  />
@Html.Raw(Model.Content.Text)
<a href="@Model.Content.Link.Url" target="@Model.Content.Link.Target">@Model.Content.Link.Name</a>`


Surface Controller` public class WidgetAfbeeldingTekstLinkSurfaceController : DocTypeGridEditorSurfaceController
    {
        public ActionResult WidgetAfbeeldingTekstLink()
        {
            WidgetAfbeeldingTekstLink widget = Model.MapTo<WidgetAfbeeldingTekstLink>();
            var viewModel = new RenderWidget<WidgetAfbeeldingTekstLink>(widget);

            return CurrentPartialView(viewModel);
        }
    }`

Works fine on the frontend...

**Comment by leekelleher** [comment]
Hi @TimGeyssens - do you know if the "previewViewPath" is set in the grid.editors.config.js?
If so, is there a partial-view for your editor?  _(I'm just trying to rule things out)_

**Comment by TimGeyssens** [comment]
Yup there is 

`{
        "name": "Afbeelding Tekst Link",
        "alias": "WidgetAfbeeldingTekstLink",
        "view": "/App_Plugins/DocTypeGridEditor/Views/DocTypeGridEditor.html",
        "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
        "icon": "icon-pictures-alt-2",
        "config": {
            "allowedDocTypes": ["widgetAfbeeldingTekstLink"],
            "enablePreview": true,
            "viewPath": "/Views/Widgets/",
            "previewViewPath": "/Views/Widgets/Previews/",
        }
    },`

**Comment by leekelleher** [comment]
Thanks Tim. Ok, so you have a partial-view at "/Views/Widgets/Previews/widgetAfbeeldingTekstLink.cshtml"?
and that's the contents of what you posted above?

I'm wondering if the surface-controller for the preview is not being hit. Would it be possible for you to set a break-point (or some kind of debugging/logging) to find out if it's being called?

**Comment by TimGeyssens** [comment]
Nope not being hit, I am also using a custom controller for the page where the dtge items are on, that is being hit.

`
    public class StandaardpaginaController: BaseController
    {
        public override ActionResult Index(RenderModel model)
        {
            Standaardpagina pagina = model.Content.MapTo<Standaardpagina>();
            var viewModel = new RenderPage<Standaardpagina>(pagina);

            return this.CurrentTemplate(viewModel);

        }
    }
`

**Comment by leekelleher** [comment]
Hmmm, interesting! (but sucks that the surface-controller isn't being hit in preview).

I haven't got time today to test it out (on an actual Umbraco install), but if you wanted to grab the DTGE source? and help debug why the previewer isn't calling the surface-controller, here are some pointers...

The Previewer will call this partial-view, [DocTypeGridEditorPreviewer.cshtml](https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditorPreviewer.cshtml), which will get the content and pass it to `Html.RenderDocTypeGridEditorItem`, (source code here: [`HtmlHelperExtensions.cs#L15`](https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/Extensions/HtmlHelperExtensions.cs#L15)).

After that there are some checks for `SurfaceControllerExists` ... which should (fingers crossed 🤞) call your surface-controller code (or not).

I'll try to schedule some time to follow up on this, it'd be good to get to the bottom of it. Thanks!

**Comment by TimGeyssens** [comment]
Thanks for the pointers, I'll take a look tomorrow and let you know what I find!

**Comment by TimGeyssens** [comment]
Well I found a workaround for the moment, I simply updated the 
`@inherits Umbraco.Web.Mvc.UmbracoViewPage<IPublishedContent>
`
in the \App_Plugins\DocTypeGridEditor\Render\DocTypeGridEditorPreviewer.cshtml to
`@inherits Umbraco.Web.Mvc.UmbracoViewPage<Geodan.RenderModels.IRenderPage<Geodan.Models.Pages.PublishedPage>>` since it was a modelbinding error

**Comment by TimGeyssens** [comment]
Yup indeed so not a bug, just good to know...

**Comment by skttl** [comment]
Would be interesting to know if we could make some kind of generic workaround. Anyone have any ideas?
