### ISSUE TITLE
Use the item picker overlay style for selecting type, on multiple doctype grid editors.

### ISSUE THREAD

**Issue by skttl** [umco/umbraco-doc-type-grid-editor#99]
When using a multiple doctype grid editor, you get a somewhat ugly select box for choosing which document type you want to use in your editor.

I think it would look a lot nicer, and make a better UX (you save a click), if you just present the available doctypes in the same style as the item picker overlay that Umbraco uses for selecting a grid editor.

So instead of this 
![image](https://user-images.githubusercontent.com/3726467/41341891-2538bb9c-6efb-11e8-9392-701e057cdebe.png)

You would get something like this
![image](https://user-images.githubusercontent.com/3726467/41341926-4311d3f6-6efb-11e8-9fc2-c70baaecf75f.png)

I will make a PR, if you like the idea :)

**Comment by mattbrailsford** [comment]
That's a cool idea, and @leekelleher actually implemented something similar for stacked content. @leekelleher do you want to share a screenshot of your implementation and maybe work out how we can port this over?

**Comment by leekelleher** [comment]
@skttl Thanks, it's a good idea.  For Stacked Content _(well, Inner Content, but it's easier to talk about Stacked Content)_, we added support for Content Templates (aka Blueprints).

> See this PR for implementation details: https://github.com/umco/umbraco-inner-content/pull/23

For the content type selector panel, we reused the same appearance as Umbraco's panel for adding new content nodes.  So you get to see the doctype's icon, name and description ... then if there are any blueprints, then those can be used.

An example would look something like this...

![capture](https://user-images.githubusercontent.com/209066/41342532-602f60c2-6ef4-11e8-8f60-7abbc88c9d42.PNG)

**Comment by skttl** [comment]
That looks awesome - I'll get working :)

**Comment by skttl** [comment]
PR added. I'm temped to take a stab at blueprints too. But I guess, that should be an issue on it's own?

**Comment by leekelleher** [comment]
Thanks @skttl! I'll close this ticket off and review & feedback on PR #100
